register_endpoint = 'https://qwallity-prod.onrender.com/register/api'
login_endopints = 'https://qwallity-prod.onrender.com/login/api'
add_course_endpoints = 'https://qwallity-prod.onrender.com/add_course/api'
get_fund_courses_endpoint = 'https://qwallity-prod.onrender.com/courses/fundamental/api'
delete_course_endpoint = f'https://qwallity-prod.onrender.com/courses/course/%s'
